# See https://pub.dev/packages/build_config

targets:
  $default:
    sources:
      - config/**
      - routes/**
      - lib/**
      - $package$
      - pubspec.*



builders:
  custom_generator:
    import: "package:custom_generator/custom_generator.dart"
    builder_factories: ["customBuilder"]
    build_extensions: { r'$package$': [ ".custom.gen.temp" ] }
    auto_apply: dependents
    build_to: source

